parameters:
- name: Environment
  type: string
- name: AzureSubscription
  type: string
- name: LiveOrNonLive
  type: string
  default: "NonLive"  
- name: ContinueEvenIfResourcesAreGettingDestroyed
  type: boolean
  default: false
- name: Container
  type: string
- name: RunTests
  type: boolean
  default: false

jobs:
- deployment: DeployApp
  timeoutInMinutes: 75
  displayName: "${{parameters.Environment}} - deploy terraform and dotnet App"
  environment: "-${{parameters.Environment}}"
  pool: $(DeploymentPool)
  container: ${{parameters.Container}}
  workspace:
    clean: all
  # variables:
  strategy:
    runOnce:
      deploy:
        steps:
          - checkout: self
            submodules: recursive

          - template: continuous-deployment.yml
            parameters:
              ContinueEvenIfResourcesAreGettingDestroyed: ${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }}
              AzureSubscription: ${{parameters.AzureSubscription}}

          - template: continuous-deployment-apim.yml
            parameters:
              ContinueEvenIfResourcesAreGettingDestroyed: ${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }}
              AzureSubscription: "UKHO-APIM-SOLAS-${{parameters.LiveOrNonLive}}"
              TerraformKeyVault: $(APIM_TERRAFORM_KEYVAULT)
              APIMResourceGroup: $(APIM_RESOURCE_GROUP_NAME)
              APIMServiceInstance: $(APIM_SERVICE_NAME)
              tfstateStorageAccountName: $(APIM_TFSTATE_STORAGE_ACCOUNT_NAME)

- deployment: FunctionalTests
  dependsOn: DeployApp
  displayName: "Run Functional Tests"
  environment: "-${{parameters.Environment}}"
  pool: $(DeploymentPool)
  container: ${{parameters.Container}}
  condition: ${{parameters.RunTests}}
  # variables:
  # strategy:
  #   runOnce:
  #     deploy:
        # steps:
        