parameters:
- name: Environment
  type: string
- name: AzureSubscription
  type: string
- name: LiveOrNonLive
  type: string
  default: "NonLive"  
- name: ContinueEvenIfResourcesAreGettingDestroyed
  type: boolean
  default: false
- name: Container
  type: string
- name: RunTests
  type: boolean
  default: false

jobs:
- deployment: DevDeployTerraform
  displayName: "Dev - Deploy Terraform"
  environment: ""
  pool: $(DeploymentPool)
  container: ${{variables.Container}}
  workspace:
    clean: all
  strategy:
          runOnce:
            deploy:
              steps:
                - template: Deployment/templates/continuous-deployment.yml
                  parameters:
                    ContinueEvenIfResourcesAreGettingDestroyed: ${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }}
                    AzureSubscription: ""

- deployment: DeployApp
  displayName: "${{parameters.Environment}} - deploy terraform and dotnet App"
  environment: "ShopFacade-${{parameters.Environment}}"
  pool: $(DeploymentPool)
  container: ${{parameters.Container}}
  workspace:
    clean: all
  variables:
    - name : WEB_APP_NAME
      value : $[ dependencies.DevDeployTerraform.outputs['DevDeployTerraform.TerraformDeploy.WEB_APP'] ]
    - name : "ErpFacadeConfiguration.BaseUrl"
      value : $[ dependencies.DevDeployTerraform.outputs['DevDeployTerraform.TerraformDeploy.ErpFacadeBaseUrl'] ]
    - name : MOCK_WEB_APP_NAME
      value : $[ dependencies.DevDeployTerraform.outputs['DevDeployTerraform.TerraformDeploy.mockWebApp'] ]
    - name : "KeyVaultSettings.ServiceUri"
      value : $[ dependencies.DevDeployTerraform.outputs['DevDeployTerraform.TerraformDeploy.keyvaulturi'] ]
   
  strategy:
    runOnce:
      deploy:
        steps:
          - checkout: self
            submodules: recursive

          - template: continuous-deployment.yml
            parameters:
              ContinueEvenIfResourcesAreGettingDestroyed: ${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }}
              AzureSubscription: ${{parameters.AzureSubscription}}

- deployment: FunctionalTests
  dependsOn:
  - DevDeployTerraform
  - DeployApp
  displayName: "Run Functional Tests"
  environment: "ShopFacade-${{parameters.Environment}}"
  pool: $(DeploymentPool)
  container: ${{parameters.Container}}
  condition: ${{parameters.RunTests}}
   variables:
      - name : ShopFacadeConfiguration.BaseUrl
        value : $[ dependencies.DevDeployTerraform.outputs['DevDeployTerraform.TerraformDeploy.ErpFacadeBaseUrl'] ]
      - name : SapMockConfiguration.BaseUrl
        value : $[ dependencies.DevDeployTerraform.outputs['DevDeployTerraform.TerraformDeploy.mockwebappurl'] ]
      - name : AzureStorageConfiguration.ConnectionString
        value : $[ dependencies.DevDeployTerraform.outputs['DevDeployTerraform.TerraformDeploy.AzureStorageConnectionString'] ]
      - name : mockWebAppName
        value : $[ dependencies.DevDeployTerraform.outputs['DevDeployTerraform.TerraformDeploy.mockWebApp'] ]
      - name : mockWebAppResourceGroup
        value : $[ dependencies.DevDeployTerraform.outputs['DevDeployTerraform.TerraformDeploy.mockWebAppResourceGroupName'] ]
        #displayName: "Dev Functional Automated Tests"
  # strategy:
  #   runOnce:
  #     deploy:
        # steps:
        workspace:
         clean: all
        steps:
          - template: Deployment/templates/continuous-testing.yml
            parameters:
              AzureSubscription: ""     
