parameters:
- name: Environment
  type: string
- name: AzureSubscription
  type: string
- name: LiveOrNonLive
  type: string
  default: "NonLive"  
- name: ContinueEvenIfResourcesAreGettingDestroyed
  type: boolean
  default: false
- name: Container
  type: string
- name: RunTests
  type: boolean
  default: false

jobs:
- deployment: DevDeployTerraform
  displayName: "terraform $(Environment) deploy "
  environment: ""
  pool: $(DeploymentPool)
  container: ${{variables.Container}}
  workspace:
    clean: all
  strategy:
          runOnce:
            deploy:
              steps:
                - template: Deployment/templates/continuous-deployment.yml
                  parameters:
                    ContinueEvenIfResourcesAreGettingDestroyed: ${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }}
                    AzureSubscription: ""

- deployment: DeployApp
  displayName: "${{parameters.Environment}} - deploy terraform and dotnet App"
  environment: "ShopFacade-${{parameters.Environment}}"
  pool: $(DeploymentPool)
  container: ${{parameters.Container}}
  workspace:
    clean: all
  variables:
    - name : WEB_APP_NAME
      value : $[ dependencies.DevDeployTerraform.outputs['DevDeployTerraform.TerraformDeploy.WEB_APP'] ]
    - name : "KeyVaultSettings.ServiceUri"
      value : $[ dependencies.DevDeployTerraform.outputs['DevDeployTerraform.TerraformDeploy.keyvaulturi'] ]
    - name : "ShopFacadeConfiguration.BaseUrl"
      value : $[ dependencies.DevDeployTerraform.outputs['DevDeployTerraform.TerraformDeploy.ShopFacadeBaseUrl'] ]
workspace:
    clean: all
strategy:
    runOnce:
      deploy:
        steps:
          - checkout: self
            submodules: recursive
          - template: Deployment/templates/continuous-deployment-app.yml
            parameters:
              ContinueEvenIfResourcesAreGettingDestroyed: ${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }}
              AzureSubscription: ${{parameters.AzureSubscription}}
