parameters:
- name: Environment
  type: string
- name: AzureSubscription
  type: string
- name: ContinueEvenIfResourcesAreGettingDestroyed
  type: boolean
  default: false
- name: Container
  type: string
- name: RunTests
  type: boolean
  default: false
- name: RunAddsTests
  type: string
  default: 'skip'
  values:
  - 'skip'
  - 'vNextIAT'
  - 'IAT'
- name: AgentPoolNameApp
  type: string
  default: "Mare Nectaris"
- name: AgentPoolNameHealthCheck
  type: string
  default: "Azure-UKHO-Engineering"
- name: AgentPoolDemandsHealthCheck
  type: string
  default: "ImageOverride -equals ubuntu-latest"

jobs:
- deployment: DeployTerraform
  displayName: "${{parameters.Environment}} - Deploy Terraform"
  environment: "ShopFacade-${{parameters.Environment}}"
  pool:
    name: ${{parameters.AgentPoolNameApp}}
  container: ${{parameters.Container}}
  variables:
    - group: "Shop-Facade-${{parameters.Environment}}"
    - group: "Shop-Facade-${{parameters.Environment}}-TF"
    - ${{ if notIn(parameters.Environment, 'PreProd', 'Live') }}:
      - group: "Shop-Facade-${{parameters.Environment}}-KV"
  workspace:
    clean: all
  strategy:
          runOnce:
            deploy:
              steps:
                - template: continuous-deployment.yml
                  parameters:
                    ContinueEvenIfResourcesAreGettingDestroyed: ${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }}
                    AzureSubscription: ${{parameters.AzureSubscription}}
                       
- deployment: DeployApp
  dependsOn: DeployTerraform
  displayName: "${{parameters.Environment}} - Deploy Dotnet App"
  environment: "ShopFacade-${{parameters.Environment}}"
  pool:
    name: ${{parameters.AgentPoolNameApp}}
  container: ${{parameters.Container}}
  workspace:
   clean: all
  variables:
    - group: "Shop-Facade-${{parameters.Environment}}"
    - group: "Shop-Facade-${{parameters.Environment}}-TF"
    - ${{ if notIn(parameters.Environment, 'PreProd', 'Live') }}:
      - group: "Shop-Facade-${{parameters.Environment}}-KV"
    - name  : WEB_APP_NAME
      value : $[ dependencies.DeployTerraform.outputs['DeployTerraform.TerraformDeploy.WEB_APP_NAME'] ]
    - name  : ResourceGroup
      value : $[ dependencies.DeployTerraform.outputs['DeployTerraform.TerraformDeploy.ResourceGroup'] ]
    - name  : WEB_APP_SLOT_NAME
      value : $[ dependencies.DeployTerraform.outputs['DeployTerraform.TerraformDeploy.WEB_APP_SLOT_NAME'] ]
    - name  : WEB_APP_SLOT_HOST_NAME
      value : $[ dependencies.DeployTerraform.outputs['DeployTerraform.TerraformDeploy.WEB_APP_SLOT_HOST_NAME'] ]
    - name  : ADDS_MOCK_WEB_APP_NAME
      value : $[ dependencies.DeployTerraform.outputs['DeployTerraform.TerraformDeploy.ADDS_MOCK_WEB_APP_NAME'] ]
  strategy:
    runOnce:
      deploy:
        steps:
          - checkout: self
            submodules: recursive
          - template: continuous-deployment-app.yml
            parameters:
              AzureSubscription: ${{parameters.AzureSubscription}}
          - pwsh: |
              Write-Host "##vso[task.setvariable variable=AzureADConfigurationAutoTestClientId;isOutput=true]$(AzureADConfigurationAutoTestClientId)"
              Write-Host "##vso[task.setvariable variable=AzureADConfigurationClientSecret;isOutput=true;issecret=true]$(AzureADConfigurationClientSecret)"
              Write-Host "##vso[task.setvariable variable=AzureADConfigurationAutoTestClientIdNoRole;isOutput=true]$(AzureADConfigurationAutoTestClientIdNoRole)"
              Write-Host "##vso[task.setvariable variable=AzureADConfigurationClientSecretNoRole;isOutput=true;issecret=true]$(AzureADConfigurationClientSecretNoRole)"
              Write-Host "##vso[task.setvariable variable=AzureADConfigurationClientId;isOutput=true]$(AzureADConfigurationClientId)"
              Write-Host "##vso[task.setvariable variable=AzureADConfigurationTenantId;isOutput=true]$(AzureADConfigurationTenantId)"
            name: SetOutputVariables

- deployment: HealthCheck
  dependsOn:  
    - DeployTerraform
    - DeployApp
  displayName: "${{parameters.Environment}} - Health Check & Slot Swap"
  environment: "ShopFacade-${{parameters.Environment}}"
  pool:
    name: ${{parameters.AgentPoolNameHealthCheck}}
    demands: ${{parameters.AgentPoolDemandsHealthCheck}}
  workspace:
   clean: all
  variables:
    - group: "Shop-Facade-${{parameters.Environment}}"
    - name  : WEB_APP_NAME
      value : $[ dependencies.DeployTerraform.outputs['DeployTerraform.TerraformDeploy.WEB_APP_NAME'] ]
    - name  : ResourceGroup
      value : $[ dependencies.DeployTerraform.outputs['DeployTerraform.TerraformDeploy.ResourceGroup'] ]
    - name  : WEB_APP_SLOT_NAME
      value : $[ dependencies.DeployTerraform.outputs['DeployTerraform.TerraformDeploy.WEB_APP_SLOT_NAME'] ]
    - name  : WEB_APP_SLOT_HOST_NAME
      value : $[ dependencies.DeployTerraform.outputs['DeployTerraform.TerraformDeploy.WEB_APP_SLOT_HOST_NAME'] ]
  strategy:
    runOnce:
      deploy:
        steps:
          - template: health-check.yml
            parameters:
              AzureSubscription: ${{parameters.AzureSubscription}}

- deployment: FunctionalTests
  dependsOn:  
    - HealthCheck
    - DeployApp
  displayName: "${{parameters.Environment}} - Functional Automated Tests"
  environment: "ShopFacade-${{parameters.Environment}}"
  pool:
    name: ${{parameters.AgentPoolNameHealthCheck}}
    demands: ${{parameters.AgentPoolDemandsHealthCheck}}
  container: ${{parameters.Container}}
  condition: and(succeeded('HealthCheck'), eq( ${{parameters.RunTests}} , 'true'))
  workspace:
   clean: all
  variables:
    - group: "Shop-Facade-${{parameters.Environment}}"
    - ${{ if notIn(parameters.Environment, 'PreProd', 'Live') }}:
      - group: "Shop-Facade-${{parameters.Environment}}-KV"
    - name  : AzureADConfigurationAutoTestClientId
      value : $[ dependencies.DeployApp.outputs['DeployApp.SetOutputVariables.AzureADConfigurationAutoTestClientId'] ]
    - name  : AzureADConfigurationAutoTestClientIdNoRole
      value : $[ dependencies.DeployApp.outputs['DeployApp.SetOutputVariables.AzureADConfigurationAutoTestClientIdNoRole'] ]
    - name  : AzureADConfigurationClientId
      value : $[ dependencies.DeployApp.outputs['DeployApp.SetOutputVariables.AzureADConfigurationClientId'] ]
    - name  : AzureADConfigurationClientSecret
      value : $[ dependencies.DeployApp.outputs['DeployApp.SetOutputVariables.AzureADConfigurationClientSecret'] ]
    - name  : AzureADConfigurationClientSecretNoRole
      value : $[ dependencies.DeployApp.outputs['DeployApp.SetOutputVariables.AzureADConfigurationClientSecretNoRole'] ]
    - name  : AzureADConfigurationTenantId
      value : $[ dependencies.DeployApp.outputs['DeployApp.SetOutputVariables.AzureADConfigurationTenantId'] ]
  strategy:
    runOnce:
      deploy:
        steps:
          - checkout: self
            submodules: recursive
          - template: continuous-testing.yml
            parameters:
              AzureSubscription: ${{parameters.AzureSubscription}}

- ${{ if ne(parameters.RunAddsTests, 'skip') }}:
  - template:  template.yml@TriggerADDSAutoTestsPipeline
    parameters:
      serviceConnection: 'addse2eauto Test - A.011.13'
      environment: ${{ parameters.RunAddsTests }}
      dependsOn:
      - DeployApp
