parameters:
# Disable the NVD dependency check job.
- name: DisableDependencyCheck
  type: boolean
  default: false

jobs:
- job: Dependencychecker
  condition: eq('${{ parameters.DisableDependencyCheck }}', false)
  workspace:
    clean: all
  displayName: "Dependencychecker"
  steps:          
    - task: UseDotNet@2
      displayName: 'Use .NET 8.0.x sdk'
      inputs:
        packageType: sdk
        useGlobalJson: true
        workingDirectory: '$(Build.SourcesDirectory)'

    - task: DotNetCoreCLI@2
      displayName: ".Net Core - NuGet restore non test projects only"
      inputs:
        command: "restore"
        projects: |
          **/*.csproj
          !**/*Tests.csproj
        feedsToUse: config
        noCache: true
        nugetConfigPath: '$(Build.SourcesDirectory)\BuildNuget.config'
        workingDirectory:
        packagesDirectory: 

    - template: dependency-checker/windows-dependency-checker.yaml@UKHOTemplates
      parameters:
        scanName: Shop-Facade
        scanPath: '$(Build.SourcesDirectory)\src'
        suppressionPath: '$(Build.SourcesDirectory)\NVDSuppressions.xml'

- job: UnitTestsAndCodeCoverage
  workspace:
    clean: all
  displayName: "Dotnet Test and Publish Code Coverage"
 
- job: BuildAndPublishAPI
  workspace:
    clean: all
  displayName: "Dotnet Build publish API"

