parameters:
# Disable the NVD dependency check job.
- name: DisableDependencyCheck
  type: boolean
  default: false

- name: DotNetVersion
  type: string
  default: '6.0.x'

jobs:
- job: Dependencychecker
  condition: eq('${{ parameters.DisableDependencyCheck }}', false)
  workspace:
    clean: all
  displayName: "Dependencychecker"
  steps:          
    - task: UseDotNet@2
      displayName: 'Use .NET SDK'
      inputs:
        packageType: sdk
        version: $(SdkVersion)

    - task: DotNetCoreCLI@2
      displayName: ".Net Core - NuGet restore non test projects only"
      inputs:
        command: "restore"
        projects: |
          **/*.csproj
          !**/*Tests.csproj
        feedsToUse: config
        noCache: true
        nugetConfigPath: '$(Build.SourcesDirectory)\BuildNuget.config'
        workingDirectory:
        packagesDirectory: 

    - template: dependency-checker/windows-dependency-checker.yaml@UKHOTemplates
      parameters:
        scanName:
        scanPath:
        suppressionPath: '$(Build.SourcesDirectory)\NVDSuppressions.xml'

- job: UnitTestsAndCodeCoverage
  workspace:
    clean: all
  displayName: "Dotnet Test and Publish Code Coverage"
 
- job: BuildAndPublishAPI
  workspace:
    clean: all
  displayName: "Dotnet Build publish API"
  
  
- job: PublishFunctionalTestsAndTerraform
  workspace:
    clean: all
  displayName: "Publish Functional Tests And Terraform"
   
- job: BuildAndPublishMockAPIAndTerraform
  workspace:
    clean: all
  displayName: "Build and Publish Mock API And Terraform"
 